// frontend-solid/src/App.tsx
import './App.css'
import {Component, createSignal, Show} from "solid-js";
import {PlayerId} from "../generated_types.ts";

const [playerId, setPlayerId] = createSignal<PlayerId>()
const [hasJoined, setHasJoined] = createSignal(false)

const App: Component = () => {
  return (
    <>
      <Show when={hasJoined()} fallback={<h1>Game Page</h1>}>
        <h1>Game Page - {playerId()}</h1>
      </Show>
      <form id="joinGame" onSubmit={(e) => {
        e.preventDefault()
        e.stopPropagation()
        setHasJoined(true)
      }}>
        <label>Player ID:
          <input type="text" name="playerId" onInput={(e) => setPlayerId(e.target.value)}></input>
        </label>
        <input type="submit">Join game</input>
      </form>
    </>
  )
}

export default App

// frontend-svelte/src/App.svelte
<script lang="ts">
    import {commander, state} from "./socket";

    let playerIdInput = ''

    function sayHello() {
        $commander.joinGame(playerIdInput)
    }
</script>

{#if !$state}
    <h1>Game Page</h1>
{:else}
    <h1>Game Page - {$state.playerId}</h1>
    <ul id="players">
        {#each $state.playersInRoom as player}
            <li>{player}</li>
        {/each}
    </ul>
    <p id="gameState">{$state.gameState}</p>
{/if}

<form id="joinGame" on:submit|preventDefault={sayHello}>
    <input type="text" name="playerId" bind:value={playerIdInput} />
    <input type="submit" value="Join game" />
</form>
